# Usamos una imagen ligera de Python
FROM python:3.9-slim

# Directorio de trabajo dentro del contenedor
WORKDIR /app

# Instalamos la librería necesaria
RUN pip install requests

# Copiamos tu script al contenedor
COPY gasto.py .

# Comando por defecto (aunque lo sobrescribiremos al ejecutar)
CMD ["python", "gasto.py"]